# Generated by Django 5.1 on 2024-09-04 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='agent',
        ),
        migrations.CreateModel(
            name='Companyinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('province_code', models.CharField(max_length=2)),
                ('area_code', models.CharField(max_length=4)),
                ('address', models.CharField(max_length=100)),
                ('phone1', models.CharField(max_length=15)),
                ('phone2', models.CharField(blank=True, max_length=15, null=True)),
                ('company_email', models.EmailField(max_length=254)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('current_activation_date', models.DateField(blank=True, null=True)),
                ('expiry_current_activation', models.DateField(blank=True, null=True)),
                ('subscription_type', models.CharField(choices=[('1', 'Free'), ('2', 'Paid')], max_length=1)),
                ('member_activation_status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], max_length=1)),
                ('notes_and_description', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
