# Generated by Django 5.1 on 2024-09-08 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0002_remove_property_agent_companyinfo_delete_agent_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Companyinfo',
        ),
    ]
